name: Analyze code

on: [push]

jobs:
  run_tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Info
        run: |
          chmod +x build.sh
          ./build.sh info
        shell: bash
      - name: Analyze
        run: |
          chmod +x build.sh
          ./build.sh analyze
        shell: bash
      - name: Try compile
        run: |
          git submodule update --init
          chmod +x build.sh
          ./build.sh
        shell: bash
