name: Compile

on: [push]

jobs:
  run_tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Setup
        run: |
          python -m pip install --upgrade pip
        shell: bash
      - name: Info
        run: |
          chmod +x build.sh
          ./build.sh info
        shell: bash
      - name: Try compile
        run: |
          git submodule update --init
          chmod +x build.sh
          ./build.sh
        shell: bash
